name: C/C++ CI

on:
  # allow manual runs
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: install
#      run: sudo apt install -y postgresql-12 postgresql-client-12 postgresql-server-dev-12 libpq-dev
    - name: make
      run: make
